# Generated by Django 6.0.2 on 2026-02-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_daily_xp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
