# Generated by Django 6.0.2 on 2026-02-16 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_gamification_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='اسم البنك', max_length=200)),
                ('account_number', models.CharField(help_text='رقم الحساب', max_length=50)),
                ('account_holder_name', models.CharField(help_text='اسم صاحب الحساب', max_length=200)),
                ('iban', models.CharField(blank=True, help_text='IBAN (اختياري)', max_length=34, null=True)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT Code (اختياري)', max_length=11, null=True)),
                ('branch_name', models.CharField(blank=True, help_text='اسم الفرع (اختياري)', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutor', models.OneToOneField(limit_choices_to={'role': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
            },
        ),
    ]
