# Generated by Django 6.0.2 on 2026-02-16 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_price_enrollment_comment_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('apple_pay', 'Apple Pay'), ('card', 'بطاقة بنكية')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
