# Generated by Django 6.0.2 on 2026-02-16 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_course_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(blank=True, help_text='الكورس المرتبط بهذا الكويز (اختياري)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course'),
        ),
        migrations.DeleteModel(
            name='CoursePayment',
        ),
    ]
